name: postgres-cloud
icon: postgres
type: db
title: Cloud PostgreSQL
external: true
options:
- version: '13'
- version: '12'
- version: '11'
- version: '10'
- version: '9.6'
labels:
- postgres
database:
  type: postgres
  kind: mariadb
  db:
    name: '{{app.name}}_{{instance.name}}'
    charset: 'UTF8'
    collation: 'en_US.UTF-8'    
  user:
    name: '{{app.name}}_{{instance.name}}'
    password: '{{password}}'
tokens:
- name: password
  generate:
    regex: '[0-9a-z-]{32}'
